
services:
  backend:
    build:
      context: . 
      dockerfile: ./TeachTrack.Api/Dockerfile 
      target: development
    ports: 
      - "8080:8080"
    volumes:
      - .:/src
      - /src/TeachTrack.Api/obj
      - /src/TeachTrack.Api/bin
      - /src/TeachTrack.Core/obj
      - /src/TeachTrack.Core/bin
      - /src/TeachTrack.Infrastructure/obj
      - /src/TeachTrack.Infrastructure/bin
      - /src/TeachTrack.Service/obj
      - /src/TeachTrack.Service/bin
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: . 
    environment:
      - HUSKY=0
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

  postgres:
    image: postgres:15-alpine
    container_name: TeachTrackContainer
    restart: always
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      start_period: 30s
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
