<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TeachTrackApi</RootNamespace>
    <UserSecretsId>a81b4617-cb95-46bc-97b0-26d7f8d8400b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeachTrack.Infrastructure\TeachTrack.Infrastructure.csproj" />
  </ItemGroup>

  <Target Name="Husky" BeforeTargets="Restore;CollectePackageReferences" Condition="'$(HUSKY)' != '0'">
    <Exec Command="dotnet tool restore" StandardOutputImportance="Low" StandardErrorImportance="High" />
    <Exec Command="dotnet husky install" StandardOutputImportance="Low" StandardErrorImportance="High" WorkingDirectory="../../" />
  </Target>

</Project>
